var that=this;function __skpm_run(e,t){that.context=t;var r=function(e){var t={};function r(n){if(t[n])return t[n].exports;var o=t[n]={i:n,l:!1,exports:{}};return e[n].call(o.exports,o,o.exports,r),o.l=!0,o.exports}return r.m=e,r.c=t,r.d=function(e,t,n){r.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:n})},r.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},r.t=function(e,t){if(1&t&&(e=r(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var n=Object.create(null);if(r.r(n),Object.defineProperty(n,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var o in e)r.d(n,o,function(t){return e[t]}.bind(null,o));return n},r.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return r.d(t,"a",t),t},r.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},r.p="",r(r.s="./src/measure.js")}({"./src/measure.js":
/*!************************!*\
  !*** ./src/measure.js ***!
  \************************/
/*! no exports provided */function(e,r,n){"use strict";n.r(r);var o=n(/*! sketch */"sketch"),s=n.n(o).a.getSelectedDocument(),a=(n(/*! sketch/ui */"sketch/ui"),s.selectedLayers),i={pasteBoard:null,init:function(){this.pasteBoard=NSPasteboard.generalPasteboard()},set:function(e){return void 0===e?null:(this.pasteBoard||this.init(),this.pasteBoard.declareTypes_owner([NSPasteboardTypeString],null),this.pasteBoard.setString_forType(e,NSPasteboardTypeString),!0)},get:function(){return this.pasteBoard||this.init(),this.pasteBoard.stringForType(NSPasteboardTypeString).toString()}};if(0===a.length)t.document.showMessage("No layers are selected.");else{var u=0;a.forEach(function(e){u+=e.frame.width*e.frame.height}),""!=u?(t.document.showMessage("Area: "+u+"px² 📐 Copied to Clipboard!"),i.set(""+u)):t.document.showMessage("No Area to Copy :(")}},sketch:
/*!*************************!*\
  !*** external "sketch" ***!
  \*************************/
/*! no static exports found */function(e,t){e.exports=require("sketch")},"sketch/ui":
/*!****************************!*\
  !*** external "sketch/ui" ***!
  \****************************/
/*! no static exports found */function(e,t){e.exports=require("sketch/ui")}});"default"===e&&"function"==typeof r?r(t):r[e](t)}that.onRun=__skpm_run.bind(this,"default");